import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};

const translations = {
    en: {
        // Navigation
        dashboard: 'Dashboard',
        inventory: 'Inventory',
        categories: 'Categories',
        suppliers: 'Suppliers',
        pos: 'Point of Sale',
        orders: 'Orders',
        reports: 'Reports',
        settings: 'Settings',
        logout: 'Logout',
        
        // Login
        login: 'Login',
        email: 'Email',
        password: 'Password',
        loginButton: 'Login',
        invalidPassword: 'Invalid password',
        userNotFound: 'User not found',
        loginFailed: 'Login failed',
        
        // Dashboard
        dailySales: 'Daily Sales',
        totalOrders: 'Total Orders',
        lowStockItems: 'Low Stock Items',
        activeCashiers: 'Active Cashiers',
        recentActivity: 'Recent Activity',
        
        // POS
        scanBarcode: 'Scan barcode or search products...',
        currentOrder: 'Current Order',
        cartEmpty: 'Cart is empty',
        subtotal: 'Subtotal',
        total: 'Total',
        proceedToCheckout: 'Proceed to Checkout',
        checkout: 'Checkout',
        totalAmount: 'Total Amount',
        paymentMethod: 'Payment Method',
        cash: 'Cash',
        card: 'Card',
        discount: 'Discount',
        completeOrder: 'Complete Order',
        orderPlacedSuccessfully: 'Order placed successfully!',
        checkoutFailed: 'Checkout failed',
        
        // Inventory
        inventoryManagement: 'Inventory Management',
        addProduct: 'Add Product',
        editProduct: 'Edit Product',
        searchProducts: 'Search products...',
        name: 'Name',
        barcode: 'Barcode',
        category: 'Category',
        price: 'Price',
        stock: 'Stock',
        actions: 'Actions',
        saveProduct: 'Save Product',
        deleteProduct: 'Delete Product',
        areYouSureDelete: 'Are you sure you want to delete this product?',
        costPrice: 'Cost Price',
        quantity: 'Quantity',
        minQuantity: 'Min Quantity',
        supplier: 'Supplier',
        selectCategory: 'Select Category',
        selectSupplier: 'Select Supplier',
        
        // Orders
        ordersHistory: 'Orders History',
        orderId: 'Order ID',
        date: 'Date',
        cashier: 'Cashier',
        allCashiers: 'All Cashiers',
        ordersLabel: 'orders',
        payment: 'Payment',
        view: 'View',
        items: 'Items',
        printReceipt: 'Print Receipt',
        
        // Reports
        dailySalesReport: 'Daily Sales Report',
        totalSalesToday: 'Total Sales Today',
        totalSales: 'Total Sales',
        totalOrdersToday: 'Total Orders Today',
        average: 'Average',
        totalDiscountToday: 'Total Discount Today',
        totalDiscount: 'Total Discount',
        todaysTransactions: "Today's Transactions",
        transactions: 'Transactions',
        time: 'Time',
        amount: 'Amount',
        show: 'Show',
        perPage: 'per page',
        showing: 'Showing',
        to: 'to',
        of: 'of',
        results: 'results',
        previous: 'Previous',
        next: 'Next',
        noTransactions: 'No transactions found for this date',
        dateRange: 'Date Range',
        from: 'From',
        selectDates: 'Select Dates',
        dates: 'dates',
        withDiscount: 'With Discount Only',
        
        // Settings
        storeSettings: 'Store Settings',
        storeName: 'Store Name',
        address: 'Address',
        vatRate: 'VAT Rate (%)',
        currency: 'Currency',
        thermalPrinterIp: 'Thermal Printer IP',
        saveSettings: 'Save Settings',
        settingsSavedSuccessfully: 'Settings saved successfully',
        failedToSaveSettings: 'Failed to save settings',
        
        // Common
        loading: 'Loading...',
        save: 'Save',
        cancel: 'Cancel',
        edit: 'Edit',
        delete: 'Delete',
        close: 'Close',
        
        // Additional Orders
        viewAndManageOrders: 'View and manage all your orders',
        totalOrdersLabel: 'Total Orders',
        totalSalesLabel: 'Total Sales',
        totalDiscounts: 'Total Discounts',
        averageOrder: 'Average Order',
        loadingOrders: 'Loading orders...',
        noOrdersFound: 'No orders found',
        noOrdersForCashier: 'No orders for this cashier',
        ordersWillAppear: 'Orders will appear here once transactions are made',
        unknown: 'Unknown',
        viewOrderDetails: 'View order details',
        unknownProduct: 'Unknown Product',
        each: 'each',
        
        // Additional Inventory
        manageProducts: 'Manage your products, stock levels, and pricing',
        totalProducts: 'Total Products',
        lowStockItemsLabel: 'Low Stock Items',
        salesPotential: 'Sales Potential',
        potentialProfit: 'Potential Profit',
        sellingPriceStock: '(Selling Price × Stock)',
        salesCost: '(Sales - Cost)',
        searchProductsPlaceholder: 'Search products by name, barcode, or category...',
        noProductsFound: 'No products found',
        getStartedAddProduct: 'Get started by adding your first product',
        product: 'Product',
        uncategorized: 'Uncategorized',
        cost: 'Cost',
        min: 'min',
        editProductTitle: 'Edit Product',
        deleteProductTitle: 'Delete Product',
        showingProducts: 'Showing {from} to {to} of {total} products',
        itemsPerPage: 'Items per page',
        addNewProduct: 'Add New Product',
        productName: 'Product Name',
        enterProductName: 'Enter product name',
        scanOrEnterBarcode: 'Scan or enter barcode',
        autoGenerate: 'Auto-generate',
        generating: 'Generating...',
        barcodeHint: 'Leave empty to auto-generate, or enter the product barcode',
        sellingPrice: 'Selling Price',
        currentStock: 'Current Stock',
        minStockLevel: 'Min. Stock Level',
        selectSupplierOptional: 'Select Supplier (Optional)',
        expiryDate: 'Expiry Date',
        updateProduct: 'Update Product',
        failedToDeleteProduct: 'Failed to delete product',
        
        // Categories
        organizeProducts: 'Organize your products into categories',
        addCategory: 'Add Category',
        totalCategories: 'Total Categories',
        active: 'Active',
        noCategoriesYet: 'No categories yet',
        getStartedCreateCategory: 'Get started by creating your first category',
        editCategory: 'Edit Category',
        deleteCategory: 'Delete Category',
        noDescription: 'No description',
        editCategoryTitle: 'Edit Category',
        addNewCategory: 'Add New Category',
        categoryName: 'Category Name',
        categoryExamples: 'e.g., Electronics, Food, Clothing',
        descriptionOptional: 'Description (Optional)',
        addDescriptionPlaceholder: 'Add a description for this category...',
        saving: 'Saving...',
        updateCategory: 'Update Category',
        createCategory: 'Create Category',
        categorySavedSuccessfully: 'Category saved successfully!',
        deleteCategoryConfirm: 'Delete this category?',
        confirmDelete: 'Confirm Delete',
        deleteCategoryWarning: 'Products in this category will be moved to "Uncategorized".',
        deleting: 'Deleting...',
        success: 'Success',
        categoryDeletedSuccessfully: 'Category deleted successfully!',
        failedToDeleteCategory: 'Failed to delete category',
        
        // Suppliers
        manageSuppliers: 'Manage your product suppliers and vendors',
        addSupplier: 'Add Supplier',
        totalSuppliers: 'Total Suppliers',
        noSuppliersYet: 'No suppliers yet',
        getStartedAddSupplier: 'Get started by adding your first supplier',
        editSupplier: 'Edit Supplier',
        deleteSupplier: 'Delete Supplier',
        contact: 'Contact',
        noContactInformation: 'No contact information',
        editSupplierTitle: 'Edit Supplier',
        addNewSupplier: 'Add New Supplier',
        supplierName: 'Supplier Name',
        supplierExample: 'e.g., ABC Trading Company',
        contactInformationOptional: 'Contact Information (Optional)',
        contactPlaceholder: 'Phone, Email, or Contact Person',
        addressOptional: 'Address (Optional)',
        supplierAddressPlaceholder: 'Supplier address...',
        updateSupplier: 'Update Supplier',
        createSupplier: 'Create Supplier',
        supplierSavedSuccessfully: 'Supplier saved successfully!',
        deleteSupplierConfirm: 'Delete this supplier?',
        
        // Dashboard
        welcome: 'Welcome',
        live: 'Live',
        loadingRecentOrders: 'Loading recent orders...',
        noRecentOrders: 'No recent orders to display',
        ordersWillAppearHere: 'Orders will appear here once transactions are made',
        orderNumber: 'Order #',
        cashierLabel: 'Cashier',
        discountLabel: 'discount',
        clickToViewDetails: 'Click to view order details',
        
        // Reports
        showOnlyDiscountedOrders: 'Show only discounted orders',
        dateSelected: 'date selected',
        datesSelected: 'dates selected',
        range: 'Range',
        
        // Settings
        manageStoreConfig: 'Manage your store configuration and preferences',
        storeInformation: 'Store Information',
        enterStoreName: 'Enter store name',
        enterStoreAddress: 'Enter store address',
        financialSettings: 'Financial Settings',
        selectStoreCurrency: 'Select your store\'s currency',
        printerSettings: 'Printer Settings',
        thermalPrinterIpAddress: 'Thermal Printer IP Address',
        enterPrinterIp: 'Enter the IP address of your thermal printer',
        loadingSettings: 'Loading settings...',
        
        // Login
        welcomeBack: 'Welcome back! Please login to continue',
        
        // Navbar
        switchToEnglish: 'Switch to English',
        switchToArabic: 'التبديل إلى العربية',
        darkMode: 'Dark Mode',
        lightMode: 'Light Mode',
        switchToDarkMode: 'Switch to Dark Mode',
        switchToLightMode: 'Switch to Light Mode',
        
        // Refund
        refund: 'Refund',
        refunded: 'Refunded',
        processRefund: 'Process Refund',
        selectItemsToRefund: 'Select Items to Refund',
        refundReason: 'Reason (Optional)',
        enterRefundReason: 'Enter reason for refund...',
        totalRefundAmount: 'Total Refund Amount',
        confirmRefund: 'Confirm Refund',
        areYouSureRefund: 'Are you sure you want to process this refund?',
        refundCannotBeUndone: 'This action cannot be undone.',
        refundProcessed: 'Refund processed successfully!',
        refundFailed: 'Failed to process refund',
        processing: 'Processing...',
        max: 'Max',
        partiallyRefunded: 'Partially Refunded',
        fullyRefunded: 'Fully Refunded',
        refundStatus: 'Refund Status',
        totalRefunded: 'Total Refunded',
        netTotal: 'Net Total',
        itemsToRefund: 'Items to Refund',
        status: 'Status',
        completed: 'Completed',
        pending: 'Pending',
        available: 'Available',
        refundedOrders: 'Refunded Orders',
        viewRefundedOrders: 'View all refunded orders and their details',
        totalRefundedOrders: 'Total Refunded Orders',
        totalRefundedAmount: 'Total Refunded Amount',
        averageRefund: 'Average Refund',
        originalAmount: 'Original Amount',
        refundedAmount: 'Refunded Amount',
        noRefundedOrders: 'No Refunded Orders Found',
        noRefundedOrdersYet: 'No refunded orders yet',
        noOrdersFoundForSearch: 'No orders found for your search',
        searchByOrderId: 'Search by Order ID...',
        dateNotAvailable: 'Date not available',
        sessionExpired: 'Your session has expired. Please log out and log back in. Would you like to log out now?',
        failedToSaveProduct: 'Failed to save product',
        
        // User Management
        userManagement: 'User Management',
        createNewUser: 'Create New User',
        addUser: 'Add User',
        userName: 'Full Name',
        enterUserName: 'Enter full name',
        userEmail: 'Email Address',
        enterUserEmail: 'Enter email address',
        userPassword: 'Password',
        enterUserPassword: 'Enter password',
        userRole: 'Role',
        selectUserRole: 'Select user role',
        admin: 'Admin',
        createUser: 'Create User',
        userCreatedSuccessfully: 'User created successfully!',
        failedToCreateUser: 'Failed to create user',
        userAlreadyExists: 'User with this email already exists',
        userManagementDescription: 'Use the button above to create new users. You can assign them either Admin or Cashier roles.',
        totalUsers: 'Total Users',
        noUsersYet: 'No users yet',
        getStartedCreateUser: 'Get started by creating your first user',
        userList: 'User List',
        createdAt: 'Created At',
        role: 'Role',
        editUser: 'Edit User',
        deleteUser: 'Delete User',
        editUserTitle: 'Edit User',
        updateUser: 'Update User',
        userUpdatedSuccessfully: 'User updated successfully!',
        failedToUpdateUser: 'Failed to update user',
        deleteUserConfirm: 'Are you sure you want to delete this user?',
        userDeletedSuccessfully: 'User deleted successfully!',
        failedToDeleteUser: 'Failed to delete user',
        cannotDeleteOwnAccount: 'You cannot delete your own account',
        passwordOptional: 'Password (Optional)',
        leaveEmptyToKeepPassword: 'Leave empty to keep current password',
    },
    ar: {
        // Navigation
        dashboard: 'لوحة التحكم',
        inventory: 'المخزون',
        categories: 'الفئات',
        suppliers: 'الموردون',
        pos: 'نقطة البيع',
        orders: 'الطلبات',
        reports: 'التقارير',
        settings: 'الإعدادات',
        logout: 'تسجيل الخروج',
        
        // Login
        login: 'تسجيل الدخول',
        email: 'البريد الإلكتروني',
        password: 'كلمة المرور',
        loginButton: 'تسجيل الدخول',
        invalidPassword: 'كلمة مرور غير صحيحة',
        userNotFound: 'المستخدم غير موجود',
        loginFailed: 'فشل تسجيل الدخول',
        
        // Dashboard
        dailySales: 'المبيعات اليومية',
        totalOrders: 'إجمالي الطلبات',
        lowStockItems: 'عناصر قليلة المخزون',
        activeCashiers: 'الكاشير النشطون',
        recentActivity: 'النشاط الأخير',
        
        // POS
        scanBarcode: 'امسح الباركود أو ابحث عن المنتجات...',
        currentOrder: 'الطلب الحالي',
        cartEmpty: 'السلة فارغة',
        subtotal: 'المجموع الفرعي',
        total: 'الإجمالي',
        proceedToCheckout: 'المتابعة إلى الدفع',
        checkout: 'الدفع',
        totalAmount: 'المبلغ الإجمالي',
        paymentMethod: 'طريقة الدفع',
        cash: 'نقدي',
        card: 'بطاقة',
        discount: 'الخصم',
        completeOrder: 'إكمال الطلب',
        orderPlacedSuccessfully: 'تم تقديم الطلب بنجاح!',
        checkoutFailed: 'فشل الدفع',
        
        // Inventory
        inventoryManagement: 'إدارة المخزون',
        addProduct: 'إضافة منتج',
        editProduct: 'تعديل منتج',
        searchProducts: 'ابحث عن المنتجات...',
        name: 'الاسم',
        barcode: 'الباركود',
        category: 'الفئة',
        price: 'السعر',
        stock: 'المخزون',
        actions: 'الإجراءات',
        saveProduct: 'حفظ المنتج',
        deleteProduct: 'حذف المنتج',
        areYouSureDelete: 'هل أنت متأكد من حذف هذا المنتج؟',
        costPrice: 'سعر التكلفة',
        quantity: 'الكمية',
        minQuantity: 'الحد الأدنى للكمية',
        supplier: 'المورد',
        selectCategory: 'اختر الفئة',
        selectSupplier: 'اختر المورد',
        
        // Orders
        ordersHistory: 'سجل الطلبات',
        orderId: 'رقم الطلب',
        date: 'التاريخ',
        cashier: 'الكاشير',
        allCashiers: 'جميع الكاشيرات',
        ordersLabel: 'طلبات',
        payment: 'الدفع',
        view: 'عرض',
        items: 'العناصر',
        printReceipt: 'طباعة الإيصال',
        
        // Reports
        dailySalesReport: 'تقرير المبيعات اليومية',
        totalSalesToday: 'إجمالي المبيعات اليوم',
        totalSales: 'إجمالي المبيعات',
        totalOrdersToday: 'إجمالي الطلبات اليوم',
        totalDiscountToday: 'إجمالي الخصم اليوم',
        totalDiscount: 'إجمالي الخصم',
        average: 'المتوسط',
        todaysTransactions: 'معاملات اليوم',
        transactions: 'المعاملات',
        time: 'الوقت',
        amount: 'المبلغ',
        show: 'عرض',
        perPage: 'لكل صفحة',
        showing: 'عرض',
        to: 'إلى',
        of: 'من',
        results: 'نتيجة',
        previous: 'السابق',
        next: 'التالي',
        noTransactions: 'لم يتم العثور على معاملات لهذا التاريخ',
        dateRange: 'نطاق التاريخ',
        from: 'من',
        selectDates: 'اختر التواريخ',
        dates: 'تواريخ',
        withDiscount: 'مع خصم فقط',
        
        // Settings
        storeSettings: 'إعدادات المتجر',
        storeName: 'اسم المتجر',
        address: 'العنوان',
        vatRate: 'معدل الضريبة (%)',
        currency: 'العملة',
        thermalPrinterIp: 'عنوان IP للطابعة الحرارية',
        saveSettings: 'حفظ الإعدادات',
        settingsSavedSuccessfully: 'تم حفظ الإعدادات بنجاح',
        failedToSaveSettings: 'فشل حفظ الإعدادات',
        
        // Common
        loading: 'جاري التحميل...',
        save: 'حفظ',
        cancel: 'إلغاء',
        edit: 'تعديل',
        delete: 'حذف',
        close: 'إغلاق',
        
        // Additional Orders
        viewAndManageOrders: 'عرض وإدارة جميع الطلبات',
        totalOrdersLabel: 'إجمالي الطلبات',
        totalSalesLabel: 'إجمالي المبيعات',
        totalDiscounts: 'إجمالي الخصومات',
        averageOrder: 'متوسط الطلب',
        loadingOrders: 'جاري تحميل الطلبات...',
        noOrdersFound: 'لم يتم العثور على طلبات',
        noOrdersForCashier: 'لا توجد طلبات لهذا الكاشير',
        ordersWillAppear: 'ستظهر الطلبات هنا بمجرد إجراء المعاملات',
        unknown: 'غير معروف',
        viewOrderDetails: 'عرض تفاصيل الطلب',
        unknownProduct: 'منتج غير معروف',
        each: 'لكل',
        
        // Additional Inventory
        manageProducts: 'إدارة منتجاتك ومستويات المخزون والأسعار',
        totalProducts: 'إجمالي المنتجات',
        lowStockItemsLabel: 'عناصر قليلة المخزون',
        salesPotential: 'إمكانات المبيعات',
        potentialProfit: 'الربح المحتمل',
        sellingPriceStock: '(سعر البيع × المخزون)',
        salesCost: '(المبيعات - التكلفة)',
        searchProductsPlaceholder: 'ابحث عن المنتجات بالاسم أو الباركود أو الفئة...',
        noProductsFound: 'لم يتم العثور على منتجات',
        getStartedAddProduct: 'ابدأ بإضافة منتجك الأول',
        product: 'المنتج',
        uncategorized: 'غير مصنف',
        cost: 'التكلفة',
        min: 'الحد الأدنى',
        editProductTitle: 'تعديل المنتج',
        deleteProductTitle: 'حذف المنتج',
        showingProducts: 'عرض {from} إلى {to} من {total} منتج',
        itemsPerPage: 'عناصر لكل صفحة',
        addNewProduct: 'إضافة منتج جديد',
        productName: 'اسم المنتج',
        enterProductName: 'أدخل اسم المنتج',
        scanOrEnterBarcode: 'امسح أو أدخل الباركود',
        autoGenerate: 'إنشاء تلقائي',
        generating: 'جاري الإنشاء...',
        barcodeHint: 'اتركه فارغاً للإنشاء التلقائي، أو أدخل باركود المنتج',
        sellingPrice: 'سعر البيع',
        currentStock: 'المخزون الحالي',
        minStockLevel: 'الحد الأدنى للمخزون',
        selectSupplierOptional: 'اختر المورد (اختياري)',
        expiryDate: 'تاريخ الانتهاء',
        updateProduct: 'تحديث المنتج',
        failedToDeleteProduct: 'فشل حذف المنتج',
        
        // Categories
        organizeProducts: 'تنظيم منتجاتك في فئات',
        addCategory: 'إضافة فئة',
        totalCategories: 'إجمالي الفئات',
        active: 'نشط',
        noCategoriesYet: 'لا توجد فئات بعد',
        getStartedCreateCategory: 'ابدأ بإنشاء فئتك الأولى',
        editCategory: 'تعديل الفئة',
        deleteCategory: 'حذف الفئة',
        noDescription: 'لا يوجد وصف',
        editCategoryTitle: 'تعديل الفئة',
        addNewCategory: 'إضافة فئة جديدة',
        categoryName: 'اسم الفئة',
        categoryExamples: 'مثال: إلكترونيات، طعام، ملابس',
        descriptionOptional: 'الوصف (اختياري)',
        addDescriptionPlaceholder: 'أضف وصفاً لهذه الفئة...',
        saving: 'جاري الحفظ...',
        updateCategory: 'تحديث الفئة',
        createCategory: 'إنشاء فئة',
        categorySavedSuccessfully: 'تم حفظ الفئة بنجاح!',
        deleteCategoryConfirm: 'حذف هذه الفئة؟',
        confirmDelete: 'تأكيد الحذف',
        deleteCategoryWarning: 'سيتم نقل المنتجات في هذه الفئة إلى "غير مصنف".',
        deleting: 'جاري الحذف...',
        success: 'نجح',
        categoryDeletedSuccessfully: 'تم حذف الفئة بنجاح!',
        failedToDeleteCategory: 'فشل حذف الفئة',
        
        // Suppliers
        manageSuppliers: 'إدارة موردي المنتجات والبائعين',
        addSupplier: 'إضافة مورد',
        totalSuppliers: 'إجمالي الموردين',
        noSuppliersYet: 'لا يوجد موردون بعد',
        getStartedAddSupplier: 'ابدأ بإضافة موردك الأول',
        editSupplier: 'تعديل المورد',
        deleteSupplier: 'حذف المورد',
        contact: 'جهة الاتصال',
        noContactInformation: 'لا توجد معلومات اتصال',
        editSupplierTitle: 'تعديل المورد',
        addNewSupplier: 'إضافة مورد جديد',
        supplierName: 'اسم المورد',
        supplierExample: 'مثال: شركة ABC التجارية',
        contactInformationOptional: 'معلومات الاتصال (اختياري)',
        contactPlaceholder: 'الهاتف، البريد الإلكتروني، أو جهة الاتصال',
        addressOptional: 'العنوان (اختياري)',
        supplierAddressPlaceholder: 'عنوان المورد...',
        updateSupplier: 'تحديث المورد',
        createSupplier: 'إنشاء مورد',
        supplierSavedSuccessfully: 'تم حفظ المورد بنجاح!',
        deleteSupplierConfirm: 'حذف هذا المورد؟',
        
        // Dashboard
        welcome: 'مرحباً',
        live: 'مباشر',
        loadingRecentOrders: 'جاري تحميل الطلبات الأخيرة...',
        noRecentOrders: 'لا توجد طلبات حديثة للعرض',
        ordersWillAppearHere: 'ستظهر الطلبات هنا بمجرد إجراء المعاملات',
        orderNumber: 'الطلب رقم',
        cashierLabel: 'الكاشير',
        discountLabel: 'خصم',
        clickToViewDetails: 'انقر لعرض التفاصيل',
        
        // Reports
        showOnlyDiscountedOrders: 'عرض الطلبات المخصومة فقط',
        dateSelected: 'تاريخ محدد',
        datesSelected: 'تواريخ محددة',
        range: 'النطاق',
        
        // Settings
        manageStoreConfig: 'إدارة إعدادات المتجر والتفضيلات',
        storeInformation: 'معلومات المتجر',
        enterStoreName: 'أدخل اسم المتجر',
        enterStoreAddress: 'أدخل عنوان المتجر',
        financialSettings: 'الإعدادات المالية',
        selectStoreCurrency: 'اختر عملة متجرك',
        printerSettings: 'إعدادات الطابعة',
        thermalPrinterIpAddress: 'عنوان IP للطابعة الحرارية',
        enterPrinterIp: 'أدخل عنوان IP لطابعتك الحرارية',
        loadingSettings: 'جاري تحميل الإعدادات...',
        
        // Login
        welcomeBack: 'مرحباً بعودتك! يرجى تسجيل الدخول للمتابعة',
        
        // Navbar
        switchToEnglish: 'Switch to English',
        switchToArabic: 'التبديل إلى العربية',
        darkMode: 'الوضع الداكن',
        lightMode: 'الوضع الفاتح',
        switchToDarkMode: 'التبديل إلى الوضع الداكن',
        switchToLightMode: 'التبديل إلى الوضع الفاتح',
        
        // Refund
        refund: 'استرداد',
        refunded: 'مسترد',
        processRefund: 'معالجة الاسترداد',
        selectItemsToRefund: 'اختر العناصر للاسترداد',
        refundReason: 'السبب (اختياري)',
        enterRefundReason: 'أدخل سبب الاسترداد...',
        totalRefundAmount: 'إجمالي مبلغ الاسترداد',
        confirmRefund: 'تأكيد الاسترداد',
        areYouSureRefund: 'هل أنت متأكد أنك تريد معالجة هذا الاسترداد؟',
        refundCannotBeUndone: 'لا يمكن التراجع عن هذا الإجراء.',
        refundProcessed: 'تم معالجة الاسترداد بنجاح!',
        refundFailed: 'فشل معالجة الاسترداد',
        processing: 'جاري المعالجة...',
        max: 'الحد الأقصى',
        partiallyRefunded: 'مسترد جزئياً',
        fullyRefunded: 'مسترد بالكامل',
        refundStatus: 'حالة الاسترداد',
        totalRefunded: 'إجمالي المسترد',
        netTotal: 'الصافي الإجمالي',
        itemsToRefund: 'العناصر للاسترداد',
        status: 'الحالة',
        completed: 'مكتمل',
        pending: 'قيد الانتظار',
        available: 'متاح',
        refundedOrders: 'الطلبات المستردة',
        viewRefundedOrders: 'عرض جميع الطلبات المستردة وتفاصيلها',
        totalRefundedOrders: 'إجمالي الطلبات المستردة',
        totalRefundedAmount: 'إجمالي المبلغ المسترد',
        averageRefund: 'متوسط الاسترداد',
        originalAmount: 'المبلغ الأصلي',
        refundedAmount: 'المبلغ المسترد',
        noRefundedOrders: 'لم يتم العثور على طلبات مستردة',
        noRefundedOrdersYet: 'لا توجد طلبات مستردة بعد',
        noOrdersFoundForSearch: 'لم يتم العثور على طلبات للبحث',
        searchByOrderId: 'البحث برقم الطلب...',
        dateNotAvailable: 'التاريخ غير متاح',
        sessionExpired: 'انتهت صلاحية جلستك. يرجى تسجيل الخروج وتسجيل الدخول مرة أخرى. هل تريد تسجيل الخروج الآن؟',
        failedToSaveProduct: 'فشل حفظ المنتج',
        
        // User Management
        userManagement: 'إدارة المستخدمين',
        createNewUser: 'إنشاء مستخدم جديد',
        addUser: 'إضافة مستخدم',
        userName: 'الاسم الكامل',
        enterUserName: 'أدخل الاسم الكامل',
        userEmail: 'البريد الإلكتروني',
        enterUserEmail: 'أدخل البريد الإلكتروني',
        userPassword: 'كلمة المرور',
        enterUserPassword: 'أدخل كلمة المرور',
        userRole: 'الدور',
        selectUserRole: 'اختر دور المستخدم',
        admin: 'مدير',
        createUser: 'إنشاء مستخدم',
        userCreatedSuccessfully: 'تم إنشاء المستخدم بنجاح!',
        failedToCreateUser: 'فشل إنشاء المستخدم',
        userAlreadyExists: 'المستخدم بهذا البريد الإلكتروني موجود بالفعل',
        userManagementDescription: 'استخدم الزر أعلاه لإنشاء مستخدمين جدد. يمكنك تعيينهم إما كمدير أو كاشير.',
        totalUsers: 'إجمالي المستخدمين',
        noUsersYet: 'لا يوجد مستخدمون بعد',
        getStartedCreateUser: 'ابدأ بإنشاء أول مستخدم',
        userList: 'قائمة المستخدمين',
        createdAt: 'تاريخ الإنشاء',
        role: 'الدور',
        editUser: 'تعديل المستخدم',
        deleteUser: 'حذف المستخدم',
        editUserTitle: 'تعديل المستخدم',
        updateUser: 'تحديث المستخدم',
        userUpdatedSuccessfully: 'تم تحديث المستخدم بنجاح!',
        failedToUpdateUser: 'فشل تحديث المستخدم',
        deleteUserConfirm: 'هل أنت متأكد أنك تريد حذف هذا المستخدم؟',
        userDeletedSuccessfully: 'تم حذف المستخدم بنجاح!',
        failedToDeleteUser: 'فشل حذف المستخدم',
        cannotDeleteOwnAccount: 'لا يمكنك حذف حسابك الخاص',
        passwordOptional: 'كلمة المرور (اختياري)',
        leaveEmptyToKeepPassword: 'اتركه فارغاً للاحتفاظ بكلمة المرور الحالية',
    }
};

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState(() => {
        const saved = localStorage.getItem('language');
        return saved || 'en';
    });

    useEffect(() => {
        localStorage.setItem('language', language);
        document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
        document.documentElement.lang = language;
    }, [language]);

    const t = (key) => {
        return translations[language]?.[key] || translations.en[key] || key;
    };

    const toggleLanguage = () => {
        setLanguage(prev => prev === 'en' ? 'ar' : 'en');
    };

    // Helper function to format dates consistently with Gregorian calendar
    const formatDate = (date, options = {}) => {
        const dateObj = date instanceof Date ? date : new Date(date);
        if (isNaN(dateObj.getTime())) return '';
        
        const locale = language === 'ar' ? 'ar-SA-u-ca-gregory' : 'en-US';
        return dateObj.toLocaleDateString(locale, options);
    };

    const formatTime = (date) => {
        const dateObj = date instanceof Date ? date : new Date(date);
        if (isNaN(dateObj.getTime())) return '';
        
        const locale = language === 'ar' ? 'ar-SA-u-ca-gregory' : 'en-US';
        return dateObj.toLocaleTimeString(locale);
    };

    const formatDateTime = (date) => {
        const dateObj = date instanceof Date ? date : new Date(date);
        if (isNaN(dateObj.getTime())) return '';
        
        const locale = language === 'ar' ? 'ar-SA-u-ca-gregory' : 'en-US';
        return dateObj.toLocaleString(locale);
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t, formatDate, formatTime, formatDateTime }}>
            {children}
        </LanguageContext.Provider>
    );
};
